# -*- coding: utf-8 -*-
"""compare.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11FOtDqwiEKK3yAIzlb4biT6s3X7BFJw0
"""

from google.colab import files
uploaded = files.upload()

with open('accuracy_knn.txt', 'r') as f:
    contentknn = f.read()
accuracy_knn = float(contentknn)
print(accuracy_knn)
with open('accuracy_nb.txt', 'r') as f:
    contentnb = f.read()
accuracy_nb = float(contentnb)
print(accuracy_nb)

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

algorithms = ['KNN', 'Naive Bayes']
accuracies = [accuracy_knn, accuracy_nb]
plt.figure(figsize=(6, 4))
sns.barplot(x=algorithms, y=accuracies, palette='Greens')
plt.title('So sánh Accuracy của KNN và Naive Bayes')
plt.ylim(0, 1)
plt.ylabel('Accuracy')
plt.xlabel('Algotithm')
plt.show()