# -*- coding: utf-8 -*-
"""navie_bayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xC2_-gxx0NZGVX63iGLlytoDMgzxLT9o
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn import preprocessing

from google.colab import files
uploaded = files.upload()

data_frame = pd.read_csv('data.csv')
data_frame.info()

X = data_frame.iloc[:,:-1].values
y = data_frame.iloc[:,-1].values
print(X)
print(y)

convert = preprocessing.MinMaxScaler()
X = convert.fit_transform(X)
print(X)

np.random.seed(42)
xtrain, xtest, ytrain, ytest = train_test_split(X,y,test_size = 0.2)

print('Dữ liệu huấn luyện')
print(xtrain)
print(ytrain)

print('Dữ liệu thử nghiệm ban đầu')
print(xtest)
print(ytest)

model = GaussianNB()
model.fit(xtrain,ytrain)
ypred = model.predict(xtest)
print(ypred)

cm = confusion_matrix(ytest,ypred)
print("Confushion Matrix")
print(cm)
print(f'\nTrue Positives (TP):   {cm[0,0]}')
print(f'False Positives (FP):  {cm[0,1]}')
print(f'False Negatives (FN):  {cm[1,0]}')
print(f'True Negatives (TN):   {cm[1,1]}\n')
print('Accuracy Score')
print(accuracy_score(ytest,ypred))

import matplotlib.pyplot as plt
import seaborn as sns

# Biểu đồ heatmap cho Confusion Matrix Naive Bayes
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens')
plt.title('Confusion Matrix - Naive Bayes')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

with open("accuracy_nb.txt", "w") as f:
    f.write(str(accuracy_score(ytest, ypred)))

from google.colab import files
files.download("accuracy_nb.txt")